"""initial_migration

Revision ID: 50b6f3225ccd
Revises: 
Create Date: 2026-06-17 19:34:30.114006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b6f3225ccd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    
    # op.create_foreign_key(None, 'tasks', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('user_table', sa.Column('reset_otp', sa.String(), nullable=True))
    op.add_column('user_table', sa.Column('otp_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'otp_expiry')
    op.drop_column('user_table', 'reset_otp')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    # ### end Alembic commands ###
