"""make password and mobile nullable for oauth

Revision ID: fb5a8f7dced4
Revises: 50b6f3225ccd
Create Date: 2026-06-20 12:42:59.878742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5a8f7dced4'
down_revision: Union[str, Sequence[str], None] = '50b6f3225ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tasks', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_table', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_table', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_user_table_mobile_number'), table_name='user_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_table_mobile_number'), 'user_table', ['mobile_number'], unique=True)
    op.alter_column('user_table', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_table', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    # ### end Alembic commands ###
