
name: FastAPI CI/CD Pipeline

# Ye batata hai ki pipeline kab chalegi (Jab master par push hoga)
on:
  push:
    branches:
      - master  

jobs:
  deploy:
    name: Auto Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        # Ye line GitHub secret se tumhara Render URL uthayegi aur usko hit karegi
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"